#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = WorldWideWeb

PROJECTVERSION = 1.1
LANGUAGE = English

APPICON = worldbook2.tiff
DOCICONS = docflash2.tiff

GLOBAL_RESOURCES = WorldWideWeb.nib docflash.tiff docflash2.tiff \
                   icon1.tiff worldbook2.tiff

CLASSES = Anchor.m FileAccess.m HTStyle.m HyperAccess.m HyperManager.m \
          HyperText.m NewsAccess.m StyleToy.m TcpAccess.m TextToy.m \
          WWWPageLayout.m

HFILES = HTAccess.h HTFile.h HTFTP.h HTParse.h HTTCP.h HTTP.h HTUtils.h \
         tcp.h WWW.h Anchor.h FileAccess.h HTStyle.h HyperAccess.h \
         HyperManager.h HyperText.h NewsAccess.h StyleToy.h TcpAccess.h \
         TextToy.h WWWPageLayout.h HTString.h

MFILES = WorldWideWeb_main.m

CFILES = HTAccess.c HTFile.c HTFTP.c HTParse.c HTString.c HTTCP.c HTTP.c



MAKEFILEDIR = /NextDeveloper/Makefiles/app
INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app worldbook2.tiff \
		-sectcreate __ICON docflash2 docflash2.tiff

LIBS = -lMedia_s -lNeXT_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


-include Makefile.preamble

include $(MAKEFILEDIR)/app.make

-include Makefile.postamble

-include Makefile.dependencies
