
/* Generated by Interface Builder */

#import <objc/Object.h>

@interface StyleToy:Object
{
    id	TabForm;
    id	ParameterForm;
    id	StylePanel;
    id	NameForm;
}

+new;

- loadDefaultStyleSheet;
- setTabForm:anObject;
- setParameterForm:anObject;
- setStylePanel:anObject;
- setNameForm:anObject;
- NextButton:sender;
- FindUnstyledButton:sender;
- ApplyButton:sender;
- heading1Button:sender;
- heading2Button:sender;
- heading3Button:sender;
- heading4Button:sender;
- heading5Button:sender;
- heading6Button:sender;
- normalButton:sender;
- addressButton:sender;
- exampleButton:sender;
- listButton:sender;
- glossaryButton:sender;
- PreviousButton:sender;
- SetButton:sender;
- PickButton:sender;
- ApplyToSimilar:sender;
- open:sender;
- saveAs:sender;
@end
